version: '3'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - 127.0.0.1:8000:80 # change ip if required
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full wordpress project
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_NAME: "sdh_srbice" #TODO set name of your database - unique per project
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "pass"
    depends_on:
      - database

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database

  database:
    image: mysql:latest
    ports:
      - 127.0.0.1:3306:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - database_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "databases"
      MYSQL_ROOT_PASSWORD: "pass"

volumes:
  database_data: